api_platform:
    title: PM-API
    version: 0.0.1
    mapping:
        paths: [
                '%kernel.project_dir%/src/Entity',
                '%kernel.project_dir%/config/api_platform'
            ]
    patch_formats:
        json: ['application/merge-patch+json']
    openapi:
        contact:
            name: 'Lukas Schönbeck'
            url: ''
            email: ''
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
