resources:
  App\Entity\User: ~
#    collectionOperations:
#      get: ~
#        normalization_context:
#          groups: [ 'read' ]
#      post: ~
#    itemOperations:
#      get: ~
#      patch: ~
  App\Entity\AsymmetricKeyPair: ~
  App\Entity\Entry: ~
